package env

import "os"

var (
	BACK_END_LOGIN_ENDPOINT        = os.Getenv("BACK_END_LOGIN_ENDPOINT")
	BACK_END_SIGN_UP_ENDPOINT      = os.Getenv("BACK_END_SIGN_UP_ENDPOINT")
	BACK_END_AUTH_USER_ENDPOINT    = os.Getenv("BACK_END_AUTH_USER_ENDPOINT")
	BACK_END_GOOGLE_AUTH_ENDPOINT  = os.Getenv("BACK_END_GOOGLE_AUTH_ENDPOINT")
	BACK_END_LOGOUT_ENDPOINT       = os.Getenv("BACK_END_LOGOUT_ENDPOINT")
	BACK_END_EDIT_PROFILE_ENDPOINT = os.Getenv("BACK_END_EDIT_PROFILE_ENDPOINT")
)

var (
	BACK_END_POST_LOGIN_URL        = BACK_END_HOST_URL + BACK_END_LOGIN_ENDPOINT
	BACK_END_POST_SIGN_UP_URL      = BACK_END_HOST_URL + BACK_END_SIGN_UP_ENDPOINT
	BACK_END_POST_EDIT_PROFILE_URL = BACK_END_HOST_URL + BACK_END_EDIT_PROFILE_ENDPOINT
	BACK_END_GET_AUTH_USER_URL     = BACK_END_HOST_URL + BACK_END_AUTH_USER_ENDPOINT
	BACK_END_GET_GOOGLE_AUTH_URL   = BACK_END_HOST_URL + BACK_END_GOOGLE_AUTH_ENDPOINT
	BACK_END_POST_LOGOUT_URL       = BACK_END_HOST_URL + BACK_END_LOGOUT_ENDPOINT
)

var (
	BACK_END_HOST_URL  = os.Getenv("BACK_END_HOST_URL")
	FRONT_END_HOST_URL = os.Getenv("FRONT_END_HOST_URL")
	PORT               = os.Getenv("PORT")
)

var (
	FRONT_END_GOOGLE_LOGIN_ENDPOINT          = os.Getenv("FRONT_END_GOOGLE_LOGIN_ENDPOINT")
	FRONT_END_GOOGLE_LOGIN_CALLBACK_ENDPOINT = os.Getenv("FRONT_END_GOOGLE_LOGIN_CALLBACK_ENDPOINT")
	FRONT_END_GOOGLE_LOGIN_URL               = FRONT_END_HOST_URL + FRONT_END_GOOGLE_LOGIN_ENDPOINT
	GOOGLE_CLIENT_ID                         = os.Getenv("GOOGLE_CLIENT_ID")
	GOOGLE_CLIENT_SECRET                     = os.Getenv("GOOGLE_CLIENT_SECRET")
	GOOGLE_REDIRECT_URL                      = FRONT_END_HOST_URL + FRONT_END_GOOGLE_LOGIN_CALLBACK_ENDPOINT
)
