package env

var (
	BACK_END_LOGIN_ENDPOINT        = "/login"
	BACK_END_SIGN_UP_ENDPOINT      = "/sign-up"
	BACK_END_AUTH_USER_ENDPOINT    = "/authuser"
	BACK_END_GOOGLE_AUTH_ENDPOINT  = "/googleauth"
	BACK_END_LOGOUT_ENDPOINT       = "/logout"
	BACK_END_EDIT_PROFILE_ENDPOINT = "/edit-profile"
)

var (
	BACK_END_POST_LOGIN_URL = BACK_END_HOST_URL + BACK_END_LOGIN_ENDPOINT

	BACK_END_POST_SIGN_UP_URL      = BACK_END_HOST_URL + BACK_END_SIGN_UP_ENDPOINT
	BACK_END_POST_EDIT_PROFILE_URL = BACK_END_HOST_URL + BACK_END_EDIT_PROFILE_ENDPOINT
	BACK_END_GET_AUTH_USER_URL     = BACK_END_HOST_URL + BACK_END_AUTH_USER_ENDPOINT
	BACK_END_GET_GOOGLE_AUTH_URL   = BACK_END_HOST_URL + BACK_END_GOOGLE_AUTH_ENDPOINT
	BACK_END_POST_LOGOUT_URL       = BACK_END_HOST_URL + BACK_END_LOGOUT_ENDPOINT
)

var (
	BACK_END_HOST_URL  = "http://localhost:8080"
	FRONT_END_HOST_URL = "http://localhost:3000"
	PORT               = "3000"
)

var (
	FRONT_END_GOOGLE_LOGIN_ENDPOINT = "/google/login"
	FRONT_END_GOOGLE_LOGIN_URL      = FRONT_END_HOST_URL + FRONT_END_GOOGLE_LOGIN_ENDPOINT
	GOOGLE_CLIENT_ID                = "104234061712-n83vudbke4h53vu17tr3khorber0qg3i.apps.googleusercontent.com"
	GOOGLE_CLIENT_SECRET            = "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"
	GOOGLE_REDIRECT_URL             = FRONT_END_HOST_URL + "/google/callback"
)
